VAGRANT:
  BOX: ubuntu/trusty64
  OS: ubuntu/trusty
  IP: 192.168.56.2
  PATH: /vagrant
  SCRIPTS_PATH: ${VAGRANT_PATH}/scripts
  UBUNTU_COMMON_SCRIPTS_PATH: ${VAGRANT_SCRIPTS_PATH}/ubuntu/common
  CONFIGS_PATH: ${VAGRANT_PATH}/configs
  UBUNTU_COMMON_CONFIGS_PATH: ${VAGRANT_CONFIGS_PATH}/ubuntu/common
  DATA_FOLDER: /vagrant_data
  OS_SCRIPTS_PATH: ${VAGRANT_SCRIPTS_PATH}/${VAGRANT_OS}
  OS_CONFIGS_PATH: ${VAGRANT_CONFIGS_PATH}/${VAGRANT_OS}
SITES:
  COUNT: 1
  BASE_DOMAIN: vagrant-common.loc
  BASE_PATH: /var/www/
  SITE_1:
    DOMAIN: ${BASE_DOMAIN}
    DIR: ${SITES_1_DOMAIN}
    PATH: ${BASE_PATH}${SITES_1_DOMAIN}/
PHP:
  VERSION: 5.6
DB:
  USER: root
  PASS: 123456q
  MARIADB_VERSION: 10.2
  MAIN:
    NAME: vagrant
    USER: vagrant_usr
    PASS: 123456q
    PROVISION_RESET: YES
PACKAGES:
  MC: NO
  HTOP: NO
  GIT: NO
  VIM: NO
  APACHE2: YES
  NGINX: YES
  MARIADB: YES
  PHP: YES
  COMPOSER: NO
  SENDMAIL: YES
  PHPMYADMIN: YES
  MAILCATCHER: YES
  DRUSH: NO
