VAGRANT:
  BOX: ubuntu/trusty64
  OS: ubuntu/trusty
  IP: 192.168.56.2
  PATH: /vagrant
  SCRIPTS_PATH: ${VAGRANT_PATH}/scripts
  UBUNTU_COMMON_SCRIPTS_PATH: ${VAGRANT_SCRIPTS_PATH}/ubuntu/common
  CONFIGS_PATH: ${VAGRANT_PATH}/configs
  UBUNTU_COMMON_CONFIGS_PATH: ${VAGRANT_CONFIGS_PATH}/ubuntu/common
  DATA_FOLDER: /vagrant_data
  OS_SCRIPTS_PATH: ${VAGRANT_SCRIPTS_PATH}/${VAGRANT_OS}
  OS_CONFIGS_PATH: ${VAGRANT_CONFIGS_PATH}/${VAGRANT_OS}
MAIN_SITE:
  DOMAIN: vagrant-common.loc
  DIR: ${MAIN_SITE_DOMAIN}
  PATH: /var/www/${MAIN_SITE_DOMAIN}
PHP:
  VERSION: 5.6
DB:
  USER: root
  PASS: 123456q
  MARIADB_VERSION: 10.2
  MAIN:
    NAME: vagrant
    USER: vagrant_usr
    PASS: 123456q
    PROVISION_RESET: YES
PACKAGES:
  MC: YES
  HTOP: YES
  GIT: YES
  VIM: YES
  APACHE2: YES
  NGINX: YES
  MARIADB: YES
  PHP: YES
  COMPOSER: YES
  SENDMAIL: YES
  PHPMYADMIN: YES
  MAILCATCHER: YES
  DRUSH: YES
