VAGRANT:
  PATH: /vagrant
  SCRIPTS_PATH: ${VAGRANT__PATH}/scripts
  CONFIGS_PATH: ${VAGRANT__PATH}/configs
  SCRIPTS_CUSTOM_PATH: ${VAGRANT__PATH}/scripts_custom
  UBUNTU_COMMON_SCRIPTS_PATH: ${VAGRANT__SCRIPTS_PATH}/ubuntu/common
  UBUNTU_COMMON_CONFIGS_PATH: ${VAGRANT__CONFIGS_PATH}/ubuntu/common
  DEBIAN_COMMON_SCRIPTS_PATH: ${VAGRANT__SCRIPTS_PATH}/debian/common
  DEBIAN_COMMON_CONFIGS_PATH: ${VAGRANT__CONFIGS_PATH}/debian/common
  DATA_FOLDER: /vagrant_data
  OS_SCRIPTS_PATH: ${VAGRANT__SCRIPTS_PATH}/${VAGRANT__OS}
  OS_CONFIGS_PATH: ${VAGRANT__CONFIGS_PATH}/${VAGRANT__OS}
SITES:
  BASE_PATH: /var/www
