VAGRANT:
  BOX: ubuntu/trusty64
  OS: ubuntu/trusty
  IP: 192.168.56.2
  CPU: 1
  MEMORY: 1024
  PATH: /vagrant
  SCRIPTS_PATH: ${VAGRANT__PATH}/scripts
  CONFIGS_PATH: ${VAGRANT__PATH}/configs
  UBUNTU_COMMON_SCRIPTS_PATH: ${VAGRANT__SCRIPTS_PATH}/ubuntu/common
  UBUNTU_COMMON_CONFIGS_PATH: ${VAGRANT__CONFIGS_PATH}/ubuntu/common
  DEBIAN_COMMON_SCRIPTS_PATH: ${VAGRANT__SCRIPTS_PATH}/debian/common
  DEBIAN_COMMON_CONFIGS_PATH: ${VAGRANT__CONFIGS_PATH}/debian/common
  DATA_FOLDER: /vagrant_data
  OS_SCRIPTS_PATH: ${VAGRANT__SCRIPTS_PATH}/${VAGRANT__OS}
  OS_CONFIGS_PATH: ${VAGRANT__CONFIGS_PATH}/${VAGRANT__OS}
SITES:
  COUNT: 1
  BASE_DOMAIN: vagrant-common.loc
  BASE_PATH: /var/www/
  SITE_1:
    DOMAIN: ${SITES__BASE_DOMAIN}
    DIR: ${SITES__SITE_1__DOMAIN}
    PATH: ${SITES__BASE_PATH}${SITES__SITE_1__DOMAIN}/
    DB:
      NAME: vagrant
      USER: vagrant_usr
      PASS: 123456q
      PROVISION_RESET: YES
PHP:
  VERSION: 5.6
DB:
  USER: root
  PASS: 123456q
  PROVISION_RESET: YES
PACKAGES:
  MC: NO
  HTOP: NO
  GIT: NO
  VIM: NO
  APACHE2: YES
  NGINX: YES
  MARIADB:
    INSTALL: YES
    VERSION: 10.2
  PHP:
    INSTALL: YES
    VERSION: 7.2
  COMPOSER: NO
  SENDMAIL: YES
  PHPMYADMIN: YES
  MAILHOG: YES
  MAILCATCHER: NO
  DRUSH:
    INSTALL: NO
    VERSION: 7.x
