VAGRANT:
  BOX: ubuntu/trusty64
  OS: ubuntu/trusty
  IP: 192.168.56.2
  OS_SCRIPTS_DIR: ${VAGRANT_SCRIPTS_DIR}/${VAGRANT_OS}
  OS_CONFIGS_DIR: ${VAGRANT_CONFIGS_DIR}/${VAGRANT_OS}
MAIN_SITE:
  DOMAIN: vagrant-common.loc
  DIR: ${MAIN_SITE_DOMAIN}
  PATH: /var/www/${MAIN_SITE_DOMAIN}
PHP:
  VERSION: 5.6
DB:
  USER: root
  PASS: 123456q
  MARIADB_VERSION: 10.3
  MAIN:
    NAME: vagrant
    USER: vagrant_usr
    PASS: 123456q
    PROVISION_RESET: YES
PACKAGES:
  MC: YES
  HTOP: YES
  GIT: YES
  VIM: YES
  APACHE2: YES
  NGINX: YES
  MARIADB: YES
  PHP5: YES
  SENDMAIL: YES
  PHPMYADMIN: YES
  MAILCATCHER: YES